
-- Elimina los objetos (No ejecutar)
/*
USE master
GO
DROP DATABASE StraadChallengingCodeAplDb
*/

-- Genera los objetos y registros (Se debe ejecutar)
/*
USE master
GO
CREATE DATABASE StraadChallengingCodeAplDb
GO
USE StraadChallengingCodeAplDb
GO
CREATE TABLE PAIS(PAIS_ID INT PRIMARY KEY IDENTITY(1,1), CODIGO NVARCHAR(5) NOT NULL UNIQUE, NOMBRE NVARCHAR(30))
CREATE TABLE CLIENTE(CLIENTE_ID INT PRIMARY KEY IDENTITY(1,1), NOMBRE NVARCHAR(30) NOT NULL, EMAIL NVARCHAR(30) NOT NULL UNIQUE, PAIS_ID INT NOT NULL)
CREATE TABLE PRODUCTO(PRODUCTO_ID INT PRIMARY KEY IDENTITY(1,1), CODIGO NVARCHAR(5) NOT NULL UNIQUE, NOMBRE NVARCHAR(30) NOT NULL, PRECIO DECIMAL(8,2) NULL, TIPO_ID INT NOT NULL)
CREATE TABLE TIPO([TIPO_ID] INT PRIMARY KEY IDENTITY(1,1), CODIGO NVARCHAR(5) NOT NULL UNIQUE, NOMBRE NVARCHAR(30) UNIQUE NOT NULL)
CREATE TABLE PEDIDO(PEDIDO_ID INT PRIMARY KEY IDENTITY(1,1), CODE NVARCHAR(5) UNIQUE, CLIENTE_ID INT NOT NULL, PRODUCTO_ID INT NOT NULL, FECHA DATE NOT NULL, TOTAL DECIMAL NOT NULL)

GO

INSERT INTO PAIS(CODIGO, NOMBRE) VALUES('MX','M XICO')
INSERT INTO PAIS(CODIGO, NOMBRE) VALUES('AR','ARGENTINA')
INSERT INTO TIPO(CODIGO, NOMBRE) VALUES('ROP','ROPA')
INSERT INTO TIPO(CODIGO, NOMBRE) VALUES('PRF','PERFUME')
INSERT INTO PRODUCTO(CODIGO, NOMBRE, PRECIO, TIPO_ID) VALUES('HDG1S', 'CAMISA POLO NEGRA', 700, (SELECT TOP(1)TIPO_ID FROM TIPO WHERE CODIGO='ROP'))
INSERT INTO PRODUCTO(CODIGO, NOMBRE, PRECIO, TIPO_ID) VALUES('PD4D7', 'PERFUME CABALLERO ', 1000, (SELECT TOP(1)TIPO_ID FROM TIPO WHERE CODIGO='ROP'))
INSERT INTO PRODUCTO(CODIGO, NOMBRE, PRECIO, TIPO_ID) VALUES('V4SR5', 'VESTIDO FLOREADO', 1000, (SELECT TOP(1)TIPO_ID FROM TIPO WHERE CODIGO='ROP'))
INSERT INTO CLIENTE(NOMBRE, EMAIL, PAIS_ID) VALUES('ALFREDO ESTRADA', 'ESTRADA-MERAZ@HOTMAIL.COM', (SELECT TOP(1)PAIS_ID FROM PAIS WHERE CODIGO='MX'))
INSERT INTO CLIENTE(NOMBRE, EMAIL, PAIS_ID) VALUES('AMANDA GUTIERREZ', 'AMANDA-GUTIERREZ@HOTMAIL.COM', (SELECT TOP(1)PAIS_ID FROM PAIS WHERE CODIGO='MX'))
INSERT INTO CLIENTE(NOMBRE, EMAIL, PAIS_ID) VALUES('PAOLA SANCHEZ', 'PAOLA SANCHEZ@HOTMAIL.COM', (SELECT TOP(1)PAIS_ID FROM PAIS WHERE CODIGO='MX'))
INSERT INTO PEDIDO(CODE, CLIENTE_ID, PRODUCTO_ID, FECHA, TOTAL) VALUES('HCOW1', 1, 1, '2023-02-10', 100)
INSERT INTO PEDIDO(CODE, CLIENTE_ID, PRODUCTO_ID, FECHA, TOTAL) VALUES('S47D5', 1, 2, '2024-05-20', 200)
INSERT INTO PEDIDO(CODE, CLIENTE_ID, PRODUCTO_ID, FECHA, TOTAL) VALUES('N5D7S', 2, 3, '2023-03-01', 200)

GO

ALTER TABLE PEDIDO ADD CONSTRAINT CN_PRODUCTO_PEDIDO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID)
ALTER TABLE CLIENTE ADD CONSTRAINT CN_PAIS_CLIENTE FOREIGN KEY (PAIS_ID) REFERENCES PAIS(PAIS_ID)
ALTER TABLE PRODUCTO ADD CONSTRAINT CN_PRODUCTO_TIPO FOREIGN KEY(TIPO_ID) REFERENCES TIPO(TIPO_ID)
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENT FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
CREATE INDEX INDX_EMAIL ON CLIENTE(EMAIL)

GO
*/

SELECT * FROM PEDIDO
SELECT C.NOMBRE AS NOMBRE, SUM(P.TOTAL) AS MONTO_TOTAL FROM CLIENTE AS C INNER JOIN PEDIDO AS P ON C.CLIENTE_ID = P.CLIENTE_ID WHERE (P.FECHA BETWEEN '2023-01-01' AND '2023-12-31')  GROUP BY(C.NOMBRE)
